development:
  url: <%= ENV.fetch('DATABASE_URL', 'mysql2://xfers:password@mysql:3306/edatest') %>
 
test:
  url: <%= ENV.fetch('DATABASE_URL', 'mysql2://xfers:password@mysql:3306/edatest') %>

production:
  url: <%= ENV.fetch('DATABASE_URL', 'mysql2://xfers:password@mysql:3306/eda') %>
