version: "3.7"
services:
    mysql:
        image: mysql:5
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: edatest
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: xfers
            MYSQL_PASSWORD: password
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    ruby:
        image: ruby:latest
        ports:
            - "3000:3000"
            - "3035:3035"
        depends_on:
            - mysql
        volumes:
            - ./rails_app:/xfers:cached
            - my-vendor:/xfers/vendor
            - my-node_modules:/xfers/node_modules
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_NAME: edatest
            DB_USERNAME: xfers
            DB_PASSWORD: password
            RAILS_ENV: development
        working_dir: /xfers
        command: >
            /bin/bash -c "apt-get -qq update \
                && apt-get -qq -f -y dist-upgrade \
                && apt-get -qq install \
                    ca-certificates \
                    curl \
                    git \
                    rsync \
                    tzdata \
                && echo '##################################################' \
                && echo 'Install nodejs' \
                && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
                && apt-get install -y nodejs \
                && echo '##################################################' \
                && echo 'Upgrade npm and install yarn' \
                && npm install -g \
                    npm@latest \
                    yarn \
                && echo '##################################################' \
                && echo 'Gem Install Foreman' \
                && gem install bundler foreman \
                && echo '##################################################' \
                && echo 'Yarn Install' \
                && yarn install \
                && echo '##################################################' \
                && echo 'Bundle Install' \
                && time bundle install --deployment --without test \
                && echo '##################################################' \
                && echo 'Bundle Rake' \
                    && time bundle exec \
                        rake db:drop \
                            db:create \
                            db:schema:load \
                            db:migrate \
                && echo '##################################################' \
                && echo 'Run Foreman' \
                && foreman start"
volumes:
  my-node_modules:
  my-vendor: