source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

# 20200502
# https://github.com/phobos/phobos
gem 'phobos'
# Use sqlite3 as the database for Active Record
#gem 'sqlite3', '~> 1.4'
gem 'mysql2', '~> 0.5'
# ActiveRecord
gem 'activerecord'

