{
 "title": "Kafka Minion OPS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_minion_topic_partition_count, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Topic Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message Count $topic",
   "type": "graph",
   "description": "Message count is only the difference between all partitions' high and low watermarks. Therefore this count is only an approximation on compact topics",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max (sum by (kubernetes_pod_name) (kafka_minion_topic_partition_message_count{topic=\"$topic\"}))",
     "legendFormat": "Approx Messages"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_minion_topic_partition_count{topic=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Cleanup Policy",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "kafka_minion_topic_partition_count{topic=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Groups consuming $topic",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "avg by (group, topic) (kafka_minion_group_topic_lag{topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Messages in $topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "avg by (topic) (sum by (topic, kubernetes_pod_name) (rate(kafka_minion_topic_partition_high_water_mark{topic=\"$topic\"}[1m])))"
    }
   ]
  },
  {
   "title": "Groups consuming $topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "avg by (topic, group) (sum by (topic, kubernetes_pod_name, group) (rate(kafka_minion_group_topic_partition_offset{topic=\"$topic\"}[1m])))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Topics by subscriber count",
   "type": "table",
   "description": "A consumer group which has at least one non expired consumer group offset for any partition is considered a \"subscriber\" for this topic. This metric can be used to identify topics which may not be consumed by anyone (anymore).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg by (topic) (kafka_minion_topic_subscribed_groups_count)"
    }
   ]
  },
  {
   "title": "Top 5 highest offset commit rates by group",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "topk(5, avg by (group) (sum by (kubernetes_pod_name, group) (rate(kafka_minion_group_topic_partition_commit_count[1m]))))"
    }
   ]
  },
  {
   "title": "Messages in by topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "avg by (topic) (sum by (topic, kubernetes_pod_name) (rate(kafka_minion_topic_partition_high_water_mark[1m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages out by topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "avg by (topic) (sum by (topic, kubernetes_pod_name) (rate(kafka_minion_group_topic_partition_offset[1m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Kafka Minion Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Offset commits processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "avg by (kubernetes_pod_name) (rate(kafka_minion_internal_kafka_messages_in_success[1m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}