source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

# 20200502
# https://github.com/phobos/phobos
gem 'phobos'

group :development, :test do
    gem 'ruby-debug-ide'
    gem 'debase'
end
