source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

# 20200511
# https://github.com/zendesk/racecar
gem 'racecar', '~> 2.0.0.beta1'

group :development, :test do
    gem 'ruby-debug-ide'
    gem 'debase'
end
group :test do
    gem 'rspec'
    gem 'timecop'
end
