global:
    scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: 
      - localhost:9090
      - kafka-exporter:9308
      - zookeeper:7071
      - broker1:7072
      - broker2:7073