global:
    scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: 
      - localhost:9090
      - kafka-minion:8100
      - zookeeper1:7061
      - zookeeper2:7062
      - broker1:7071
      - broker2:7072
      - broker3:7073